controls:
  ButtonControl:
    display_name: Button
    category: all
  TextboxControl:
    display_name: Textfield
    category: all
  HeadingControl:
    display_name: Headings
    category: all
  AlertControl:
    display_name: Alert
    category: all
